/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import java.time.LocalDate

fun main() {
    println("¡Hola, Kotlin!")
    val nombre: String = "Santino"
    var fecha = LocalDate.now()
    println("Hola soy $nombre y hoy es $fecha")
}

