/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import java.time.LocalDate

fun main() {
    //Paso 1
    println("¡Hola, Kotlin!")

    val nombre: String = "Santino"
    var fecha = LocalDate.now()
    println("Hola soy $nombre y hoy es $fecha")

    //Paso 2
    val Minombre: String = "Santi"
    val edad: Int = 16
    val peso: Double = 72.5
    val juegaFutbol: Boolean = true
    
    println("Soy $Minombre, tengo $edad años y peso $peso kg. ¿Juego futbol? $juegaFutbol")

    var base: Double= 10.8
    var altura: Double= 50.5
    var area: Double= base*altura

    println("El área del rectángulo es $area")

    //Paso 3
    fun esParOImpar(numero: Int): String {
    return when {
        numero % 2 == 0 -> "Par"
        else -> "Impar"
    }
    }

    val number:Int=0
 
    if (number > 0) {
        println("Positivo")
    } else if (number < 0) {
        println("Negativo")
    } else if (number == 0) {
        println("El número es cero")
    }

    //Paso 4
    fun mostrarNumerosConLoops() {
    // Usando for
    println("Usando for:")
    for (i in 1..10) {
        println(i)
    }
    
    // Usando while
    println("\nUsando while:")
    var j = 1
    while (j <= 10) {
        println(j)
        j++
    }
    
    // Usando do-while
    println("\nUsando do-while:")
    var k = 1
    do {
        println(k)
        k++
    } while (k <= 10)
}   

    for (i in 2..20){
        if (i % 2 == 0){
            println(i)
    }

    var j = 2
        while (j <= 20) {
         println(j)
            j += 2
     }

    var k = 2
    do{
        println(k)
        k+=2
    } while (k <= 20)
}
}


        
